service: scraper-api #name this whatever you want
 
provider:
 name: aws
 runtime: python3.11
 stage: dev
 region: us-east-1
 memorySize: 128
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   timeout: 60
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY /{proxy+}'
